#!/usr/bin/env python
"""

    syntax:
        comma seperated list of args

        args:
            <short name>(<long name>)[<type>]=<default>

        all but short name are optional
        if long name is missing, short name will be used
        if long name is missing, and short name has len > 1
            long name will be short name and short name will be the
            first character of short name

    examples:
        f(foo)[int]=10
        f[int]=10

"""


import argparse


type_lookup = {'int': int, 'str': str, 'bool': bool, 'float': float, \
        'long': long, 'complex': complex, 'unicode': unicode, \
        'list': list, 'tuple': tuple, 'bytearray': bytearray, \
        'buffer': buffer, 'set': set, 'frozenset': frozenset, \
        'dict': dict, 'memoryview': memoryview}


def lookup_type(typestring):
    if typestring in type_lookup:
        return type_lookup[typestring]
    raise TypeError("Unknown type string: %s" % typestring)


def parse_token(token):
    """
    Return args and kwargs for ArgumentParser.add_argument
    """
    if '=' in token:
        token, default = token.split('=')
    else:
        default = None

    if '[' in token:
        token, dtype = token.split('[')
        dtype = dtype[:-1]  # remove ']'
        dtype = lookup_type(dtype)
    else:
        dtype = str

    if '(' in token:
        sname, lname = token.split('(')
        lname = lname[:-1]
    else:
        sname = token[0]
        lname = token
    if default is not None:
        default = dtype(default)

    args = ('-%s' % sname, '--%s' % lname)
    return args, dict(type=dtype, default=default)


def parse(arg_string, description=None):
    """
    make an argparser from arg_string
    """
    if description is None:
        description = "Autogenerated parser from string: %s" % arg_string
    parser = argparse.ArgumentParser(description=description)
    for t in arg_string.split(','):
        args, kwargs = parse_token(t)
        parser.add_argument(*args, **kwargs)
    return parser


def get(arg_string, args=None, namespace=None, \
        partial=False, return_leftover=False):
    p = parse(arg_string)
    if partial:
        ns, leftover = p.parse_known_args(args, namespace)
        if return_leftover:
            return ns, leftover
        return ns
    return p.parse_args(args, ns)
